from __future__ import annotations

import base64
import logging
import asyncio
import time
import sys
from contextlib import suppress
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, UploadFile, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.config import get_settings
from app.models import ClientAudioMessage, ClientInterruptMessage, ClientTextMessage, ImageAnnotationResponse, ServerMessage
from app.services.pipeline import VoicePipeline
from app.services.runtime_status import get_vram_status
from app.services.vision_service import VisionAnnotator


class _DuplicateLogFilter(logging.Filter):
    def __init__(self, window_seconds: float = 0.5) -> None:
        super().__init__()
        self.window_seconds = window_seconds
        self._last_signature: tuple[str, int, str] | None = None
        self._last_time = 0.0

    def filter(self, record: logging.LogRecord) -> bool:
        msg = record.getMessage()
        signature = (record.name, record.levelno, msg)
        now = time.monotonic()
        if self._last_signature == signature and (now - self._last_time) <= self.window_seconds:
            return False
        self._last_signature = signature
        self._last_time = now
        return True


logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s", force=True)
_root_logger = logging.getLogger()
_root_logger.addFilter(_DuplicateLogFilter())

_app_logger = logging.getLogger("app")
_app_logger.handlers.clear()
_app_handler = logging.StreamHandler(sys.stderr)
_app_handler.setFormatter(logging.Formatter("%(levelname)s %(name)s: %(message)s"))
_app_logger.addHandler(_app_handler)
_app_logger.setLevel(logging.INFO)
_app_logger.propagate = False

logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpcore").setLevel(logging.WARNING)


settings = get_settings()
app = FastAPI(title="MTR-Insight Inspection Voice Assistant")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[settings.cors_origin],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve extracted anomaly images from inspection reports. The URL prefix
# mirrors the on-disk directory name (reports/extracted_images).
_images_dir = Path(settings.reports_dir) / "extracted_images"
if _images_dir.exists():
    app.mount("/reports/extracted_images", StaticFiles(directory=str(_images_dir)), name="report_extracted_images")

# Serve the annotated per-frame result images (and other report artifacts) that
# live at the reports/ root, e.g. reports/143_result.jpg -> /reports/reference/143_result.jpg.
# The numeric prefix is the ground-truth image id (the report's "Frame N").
_reports_dir = Path(settings.reports_dir)
if _reports_dir.exists():
    app.mount("/reports/reference", StaticFiles(directory=str(_reports_dir)), name="report_reference_images")

# Serve source camera frames referenced by observations.image_path.
_inspection_img_dir = Path(settings.inspection_image_dir)
if _inspection_img_dir.exists():
    app.mount("/inspection/images", StaticFiles(directory=str(_inspection_img_dir)), name="inspection_images")

# Serve vision-annotated images generated by the annotate_image tool.
_annotated_img_dir = Path(settings.annotated_image_cache_dir)
_annotated_img_dir.mkdir(parents=True, exist_ok=True)
app.mount("/annotated/images", StaticFiles(directory=str(_annotated_img_dir)), name="annotated_images")

pipeline = VoicePipeline(settings)
vision_annotator = VisionAnnotator(settings)
_models_loaded = False
_models_loading = False
_preload_lock = asyncio.Lock()


async def _preload_models() -> dict[str, bool]:
    """Preload all models (LLM and TTS voices)."""
    global _models_loaded, _models_loading
    if _models_loaded:
        return {"llm": True, "english": True, "chinese": True}

    async with _preload_lock:
        if _models_loaded:
            return {"llm": True, "english": True, "chinese": True}
        if _models_loading:
            return {}

        _models_loading = True
        try:
            _app_logger.info("Starting model preload...")
            llm_loaded = await pipeline.llm.preload_model()
            tts_loaded = pipeline.tts.preload_voices()
            _models_loaded = llm_loaded and tts_loaded.get("english", False) and tts_loaded.get("chinese", False)
            _app_logger.info(
                "Model preload complete: llm=%s, english=%s, chinese=%s",
                llm_loaded,
                tts_loaded.get("english"),
                tts_loaded.get("chinese"),
            )
            return {"llm": llm_loaded, **tts_loaded}
        except Exception as exc:
            _app_logger.exception("Model preload failed: %s", exc)
            _models_loaded = False
            return {}
        finally:
            _models_loading = False


async def _runtime_snapshot() -> dict[str, object]:
    llm_state = await pipeline.llm.runtime_status()
    gpu_state = get_vram_status()
    tts_state = pipeline.tts.runtime_status()
    return {
        "status": "ok",
        "models_loaded": _models_loaded,
        "models_loading": _models_loading,
        **llm_state,
        **tts_state,
        **gpu_state,
    }


@app.on_event("startup")
async def on_startup() -> None:
    asyncio.create_task(_preload_models())


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/reports/image-list")
def report_image_list() -> dict[str, list[str]]:
    """Return URLs of anomaly images from inspection reports.

    Combines legacy reports/extracted_images/ with the annotated per-frame
    result images at the reports/ root (<gt_image_id>_result.jpg — the same
    frames as the database's gt images, with anomaly bboxes drawn on)."""
    urls: list[str] = []
    images_dir = Path(settings.reports_dir) / "extracted_images"
    if images_dir.exists():
        names = sorted(p.name for p in images_dir.iterdir() if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png"})
        urls.extend(f"/reports/extracted_images/{name}" for name in names)
    reports_dir = Path(settings.reports_dir)
    if reports_dir.exists():
        names = sorted(
            p.name for p in reports_dir.iterdir()
            if p.is_file() and p.name.endswith("_result.jpg")
        )
        urls.extend(f"/reports/reference/{name}" for name in names)
    return {"images": urls}


@app.get("/status")
async def runtime_status() -> dict[str, object]:
    return await _runtime_snapshot()


@app.get("/voices")
def voices() -> dict[str, object]:
    return {
        "default_voice": pipeline.tts.default_model_path,
        "chinese_voice": pipeline.tts.chinese_model_path,
        "chinese_fallback_voice": pipeline.tts.chinese_fallback_model_path,
        "voices": pipeline.tts.list_available_voices(),
    }


@app.post("/annotate-image", response_model=ImageAnnotationResponse)
async def annotate_image(
    image: UploadFile = File(...),
    question: str = Form("What anomalies are in this image?"),
) -> dict[str, object]:
    """Upload an image, ask a question, and receive the image back with anomaly annotations."""
    if not image.content_type or not image.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Uploaded file must be an image")

    try:
        image_bytes = await image.read()
        if len(image_bytes) == 0:
            raise HTTPException(status_code=400, detail="Uploaded image is empty")

        result = await vision_annotator.annotate(image_bytes, question)
        return result
    except HTTPException:
        raise
    except Exception as exc:
        _app_logger.exception("Image annotation failed: %s", exc)
        raise HTTPException(status_code=500, detail=f"Image annotation failed: {exc}") from exc


@app.websocket("/ws")
async def websocket_chat(ws: WebSocket) -> None:
    await ws.accept()
    # Ensure preload runs and push status once it completes.
    async def preload_and_notify() -> None:
        await _preload_models()
        with suppress(Exception):
            await ws.send_json({"type": "runtime_update", "runtime": await _runtime_snapshot()})

    asyncio.create_task(preload_and_notify())
    await ws.send_json(ServerMessage(type="ready", runtime=await _runtime_snapshot()).model_dump(exclude_none=True))
    active_task = None
    selected_voice_model: str | None = None
    conversation_history: list[tuple[str, str]] = []
    tool_call_history: list[dict[str, object]] = []

    async def cancel_active(reason: str, request_id: str | None = None) -> None:
        nonlocal active_task
        if active_task and not active_task.done():
            active_task.cancel()
            with suppress(asyncio.CancelledError):
                await active_task
        active_task = None
        await ws.send_json(
            ServerMessage(type="interrupted", reason=reason, request_id=request_id).model_dump(exclude_none=True)
        )

    async def stream_audio_request(audio_bytes: bytes, suffix: str) -> None:
        user_text = ""
        assistant_text = ""
        current_request_id: str | None = None
        last_tool_payload: dict[str, object] | None = None

        def send_tool_calls(payload: dict[str, object]) -> None:
            nonlocal last_tool_payload
            last_tool_payload = payload
            asyncio.create_task(
                ws.send_json(
                    ServerMessage(
                        type="tool_calls",
                        tool_calls=payload.get("tool_calls"),
                        tool_router_raw=payload.get("tool_router_raw"),
                        highlight=payload.get("highlight"),
                        request_id=current_request_id,
                    ).model_dump(exclude_none=True)
                )
            )

        async for event in pipeline.handle_audio(
            audio_bytes,
            suffix=suffix,
            voice_model_path=selected_voice_model,
            chat_history=conversation_history,
            tool_history=tool_call_history,
            tool_calls_callback=send_tool_calls,
        ):
            if event.type == "transcript":
                user_text = event.transcript or ""
                current_request_id = event.request_id
            elif event.type == "llm_done":
                assistant_text = event.text or ""
            await ws.send_json(event.model_dump(exclude_none=True))

        if user_text.strip() and assistant_text.strip():
            conversation_history.append((user_text, assistant_text))
            if len(conversation_history) > 12:
                del conversation_history[:-12]
        if last_tool_payload and last_tool_payload.get("tool_calls"):
            tool_call_history.append(last_tool_payload)
            if len(tool_call_history) > 6:
                del tool_call_history[:-6]

    async def stream_text_request(text: str) -> None:
        user_text = ""
        assistant_text = ""
        current_request_id: str | None = None
        last_tool_payload: dict[str, object] | None = None

        def send_tool_calls(payload: dict[str, object]) -> None:
            nonlocal last_tool_payload
            last_tool_payload = payload
            asyncio.create_task(
                ws.send_json(
                    ServerMessage(
                        type="tool_calls",
                        tool_calls=payload.get("tool_calls"),
                        tool_router_raw=payload.get("tool_router_raw"),
                        highlight=payload.get("highlight"),
                        request_id=current_request_id,
                    ).model_dump(exclude_none=True)
                )
            )

        async for event in pipeline.handle_text(
            text,
            voice_model_path=selected_voice_model,
            chat_history=conversation_history,
            tool_history=tool_call_history,
            tool_calls_callback=send_tool_calls,
        ):
            if event.type == "transcript":
                user_text = event.transcript or ""
                current_request_id = event.request_id
            elif event.type == "llm_done":
                assistant_text = event.text or ""
            await ws.send_json(event.model_dump(exclude_none=True))

        if user_text.strip() and assistant_text.strip():
            conversation_history.append((user_text, assistant_text))
            if len(conversation_history) > 12:
                del conversation_history[:-12]
        if last_tool_payload and last_tool_payload.get("tool_calls"):
            tool_call_history.append(last_tool_payload)
            if len(tool_call_history) > 6:
                del tool_call_history[:-6]

    try:
        while True:
            payload = await ws.receive_json()
            message_type = payload.get("type")
            if message_type == "ping":
                # Application-level heartbeat from the frontend.
                await ws.send_json({"type": "pong", "timestamp": payload.get("timestamp")})
                continue

            if message_type == "interrupt":
                interrupt = ClientInterruptMessage.model_validate(payload)
                await cancel_active(reason="user_interrupt", request_id=interrupt.request_id)
                continue

            if message_type == "set_voice":
                requested_voice = payload.get("voice_id")
                resolved = pipeline.tts.resolve_voice_model(requested_voice)
                if not resolved:
                    await ws.send_json(
                        ServerMessage(type="error", error=f"Unknown voice: {requested_voice}").model_dump(exclude_none=True)
                    )
                    continue
                selected_voice_model = resolved
                await ws.send_json(
                    {
                        "type": "voice_selected",
                        "voice_id": requested_voice,
                        "voice_model_path": resolved,
                    }
                )
                continue

            if message_type == "clear_context":
                if active_task and not active_task.done():
                    await cancel_active(reason="context_cleared")

                conversation_history.clear()
                await ws.send_json({"type": "context_cleared"})
                continue

            if message_type == "user_audio":
                message = ClientAudioMessage.model_validate(payload)
                audio_bytes = base64.b64decode(message.audio_base64)
                suffix = ".webm" if "webm" in message.mime_type.lower() else ".wav"
                if active_task and not active_task.done():
                    await cancel_active(reason="new_request")
                active_task = pipeline_task = asyncio.create_task(stream_audio_request(audio_bytes, suffix))
            elif message_type == "user_text":
                text_message = ClientTextMessage.model_validate(payload)
                text = (text_message.text or "").strip()
                if not text:
                    continue
                if active_task and not active_task.done():
                    await cancel_active(reason="new_request")
                active_task = pipeline_task = asyncio.create_task(stream_text_request(text))
            else:
                continue

            def _done_cb(task):
                if task.cancelled():
                    return
                exc = task.exception()
                if exc is not None:
                    logging.getLogger(__name__).exception("Pipeline task failed: %s", exc)

            pipeline_task.add_done_callback(_done_cb)

    except WebSocketDisconnect:
        if active_task and not active_task.done():
            active_task.cancel()
        return
    except Exception as exc:  # noqa: BLE001
        await ws.send_json(ServerMessage(type="error", error=str(exc)).model_dump())
